ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER DB_SINESPCT IDENTIFIED BY DB_SINESPCT;

CREATE USER DB_SISCN IDENTIFIED BY DB_SISCN;

GRANT CONNECT, RESOURCE TO DB_SISCN;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO DB_SISCN;

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_ARQUIVOS ( 
	ID_CADASTRO_NACIONAL_ARQUIVOS INTEGER   NOT NULL,
	DT_VALIDADE          DATE   ,
	NO_ARQUIVO_URL       VARCHAR2(400)   ,
	ID_CADASTRO_NACIONAL_TIPO_ARQUIVO INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_3 PRIMARY KEY ( ID_CADASTRO_NACIONAL_ARQUIVOS ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_2 UNIQUE ( ID_CADASTRO_NACIONAL_TIPO_ARQUIVO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_3 UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_CONTATOS ( 
	ID_CADASTRO_NACIONAL_CONTATOS INTEGER   NOT NULL,
	ED_CONTATO           VARCHAR2(200)   NOT NULL,
	ID_CN_TIPO_CONTATO   INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_1 PRIMARY KEY ( ID_CADASTRO_NACIONAL_CONTATOS ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CN_TIPO_C UNIQUE ( ID_CN_TIPO_CONTATO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_0 UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_ENDERECO ( 
	ID_CADASTRO_NACIONAL_ENDERECO INTEGER   NOT NULL,
	ED_LOGRADOURO        VARCHAR2(200)   ,
	ED_COMPLEMENTO       VARCHAR2(200)   ,
	ED_BAIRRO            VARCHAR2(100)   ,
	ED_NUMERO            VARCHAR2(20)   ,
	NR_CEP               NUMBER(8)   ,
	ID_MUNICIPIO         NUMBER(19)   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_0 PRIMARY KEY ( ID_CADASTRO_NACIONAL_ENDERECO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_MUNICIPIO UNIQUE ( ID_MUNICIPIO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_LEGAL ( 
	ID_CADASTRO_NACIONAL_REPRESENTANTE_LEGAL INTEGER   NOT NULL,
	NO_NOME              VARCHAR2(200)   NOT NULL,
	NR_TERMINO_MANDATO   INTEGER   ,
	TP_PAPEL_DIRETORIA   INTEGER   NOT NULL,
	DT_NASCIMENTO        DATE   ,
	CO_CPF               CHAR(11)   NOT NULL,
	CO_TELEFONE          VARCHAR2(100)   ,
	CO_EMAIL             VARCHAR2(100)   NOT NULL,
	TP_ESCOLARIDADE      INTEGER   ,
	CO_CURSO             VARCHAR2(20)   ,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CONSTRAINT PK_CN_REPRESENT PRIMARY KEY ( ID_CADASTRO_NACIONAL_REPRESENTANTE_LEGAL ) ,
	CONSTRAINT UNQ_CN_REPRESENT_ID_CADASTRO UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_TECNICO ( 
	ID_CADASTRO_NACIONAL_REPRESENTANTE_TECNICO INTEGER   NOT NULL,
	NO_NOME              VARCHAR2(100)   NOT NULL,
	DT_NASCIMENTO        DATE   NOT NULL,
	CO_CPF               NUMBER(11)   NOT NULL,
	ED_TELEFONE          VARCHAR2(50)   NOT NULL,
	ED_EMAIL             VARCHAR2(50)   NOT NULL,
	TP_ESCOLARIDADE      INTEGER   NOT NULL,
	CO_PROFISSAO         INTEGER   NOT NULL,
	TP_POSSUI_EXPERIENCIA INTEGER   NOT NULL,
	ID_RESPONSAVEL_PRINCIPAL INTEGER   ,
	ID_OWNER             INTEGER   NOT NULL,
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CONSTRAINT PK_CADASTRO_NAC_2 PRIMARY KEY ( ID_CADASTRO_NACIONAL_REPRESENTANTE_TECNICO ) ,
	CONSTRAINT UNQ_CADASTRO_NAC_ID_CADASTRO_1 UNIQUE ( ID_CADASTRO_NACIONAL ) 
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_TIPO_ARQUIVO ( 
	ID_CADASTRO_NACIONAL_TIPO_ARQUIVO INTEGER   NOT NULL,
	DS_TIPO_ARQUIVO      VARCHAR2(100)   ,
	CONSTRAINT PK_CADASTRO_NAC_4 PRIMARY KEY ( ID_CADASTRO_NACIONAL_TIPO_ARQUIVO ) ,
	CONSTRAINT FK_CADASTRO_NACIONAL_TIPO_ARQUIVO_CADASTRO_NACIONAL_ARQUIVOS FOREIGN KEY ( ID_CADASTRO_NACIONAL_TIPO_ARQUIVO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_ARQUIVOS( ID_CADASTRO_NACIONAL_TIPO_ARQUIVO )    
 );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL_TIPO_CONTATO ( 
	ID_CADASTRO_NACIONAL_TIPO_CONTATO INTEGER   NOT NULL,
	NO_TIPO_CONTATO      VARCHAR2(50)   ,
	CONSTRAINT PK_CN_TIPO_CONT PRIMARY KEY ( ID_CADASTRO_NACIONAL_TIPO_CONTATO ) ,
	CONSTRAINT FK_CN_TIPO_CONTATO_CADASTRO_NACIONAL_CONTATOS FOREIGN KEY ( ID_CADASTRO_NACIONAL_TIPO_CONTATO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_CONTATOS( ID_CN_TIPO_CONTATO )    
 );

CREATE  TABLE DB_SINESPCT.MUNICIPIO ( 
	ID_MUNICIPIO         NUMBER(19)   NOT NULL,
	CO_MUNICIPIO         NUMBER(10)   ,
	NO_MUNICIPIO         VARCHAR2(50)   ,
	ID_UF                NUMBER(19)   NOT NULL,
	CO_MUNICIPIO_IBGE    VARCHAR2(7)   ,
	CONSTRAINT FK_MUNICIPIO_CADASTRO_NACIONAL_ENDERECO FOREIGN KEY ( ID_MUNICIPIO ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_ENDERECO( ID_MUNICIPIO )    
 );

CREATE UNIQUE INDEX IX_PK_MUNICIPIO ON DB_SINESPCT.MUNICIPIO ( ID_MUNICIPIO );

CREATE  TABLE DB_SINESPCT.CADASTRO_NACIONAL ( 
	ID_CADASTRO_NACIONAL INTEGER   NOT NULL,
	CO_CNPJ              CHAR(14)   ,
	CO_TIPO_ENTIDADE     INTEGER   NOT NULL,
	NR_FILIAIS           INTEGER  DEFAULT 0 NOT NULL,
	NO_NOME_FANTASIA     VARCHAR2(200)   NOT NULL,
	NO_RAZAO_SOCIAL      VARCHAR2(200)   ,
	CO_CNAE_PRINCIPAL    VARCHAR2(50)   ,
	CO_CNAE_SECUNDARIO   VARCHAR2(50)   ,
	VL_RECEITA_BRUTA     NUMBER(18,2)   NOT NULL,
	TP_MODALIDADE_FINANCIAMENTO INTEGER   NOT NULL,
	CO_MODALIDADE        INTEGER   ,
	CO_MODALIDADE_OUTROS INTEGER   ,
	TP_FINANCIAMENTO_ESTADO INTEGER   NOT NULL,
	CO_FINANCIAMENTO_ESTADO VARCHAR2(50)   ,
	TP_FINANCIAMENTO_MUNICIPIO INTEGER   ,
	CO_FINANCIAMENTO_MUNICIPIO INTEGER   ,
	TP_DOACOES_OUTRAS    INTEGER   ,
	ED_DOACOES_OUTRAS_DETALHES VARCHAR2(100)   ,
	VL_DOACOES_OUTRAS_MEDIA NUMBER(18,2)   ,
	TP_DOACOES_OUTRAS_RECEITAS INTEGER   ,
	VL_DOACOES_OUTRAS_RECEITAS_MEDIA INTEGER   ,
	ED_DOACOES_OUTRAS_RECEITAS_OUTRAS VARCHAR2(50)   ,
	VL_DOACOES_OUTRAS_MEDIA_2 NUMBER(18,2)   ,
	DS_URL_LICENCA_SANITARIA VARCHAR2(400)   ,
	DT_VALIDADE_LICENCA_SANITARIA DATE   ,
	NR_PRAZO_PROJETO     INTEGER   NOT NULL,
	DS_URL_PROJETO_TERAPEUTICO VARCHAR2(400)   ,
	TP_POSSUI_CEBAS      INTEGER   NOT NULL,
	DT_INICIO_VALIDADE_CEBAS DATE   ,
	DT_FIM_VALIDADE_CEBAS DATE   ,
	DS_URL_DOCUMENTO_CEBAS VARCHAR2(400)   ,
	TP_CEBAS_DEPAD       INTEGER   ,
	NU_ANO_PROTOCOLO_CEBAS INTEGER   ,
	NU_PROTOCOLO_CEBAS   INTEGER   ,
	TP_CUMPRE_CONAD      INTEGER   ,
	NU_TOTAL_VAGAS       INTEGER   ,
	CONSTRAINT PK_CADASTRO_NAC PRIMARY KEY ( ID_CADASTRO_NACIONAL ) ,
	CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_ENDERECO FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_ENDERECO( ID_CADASTRO_NACIONAL )    ,
	CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_CONTATOS FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_CONTATOS( ID_CADASTRO_NACIONAL )    ,
	CONSTRAINT FK_CADASTRO_NACIONAL_CN_REPRESENTANTE_LEGAL FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_LEGAL( ID_CADASTRO_NACIONAL )    ,
	CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_REPRESENTANTE_TECNICO FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_REPRESENTANTE_TECNICO( ID_CADASTRO_NACIONAL )    ,
	CONSTRAINT FK_CADASTRO_NACIONAL_CADASTRO_NACIONAL_ARQUIVOS FOREIGN KEY ( ID_CADASTRO_NACIONAL ) REFERENCES DB_SINESPCT.CADASTRO_NACIONAL_ARQUIVOS( ID_CADASTRO_NACIONAL )    
 );

COMMENT ON COLUMN DB_SINESPCT.CADASTRO_NACIONAL_ENDERECO.ID_MUNICIPIO IS 'Identificador do Município no sistema.';

COMMENT ON TABLE DB_SINESPCT.MUNICIPIO IS 'Representa as informações de um Município no sistema.';

COMMENT ON COLUMN DB_SINESPCT.MUNICIPIO.ID_MUNICIPIO IS 'Identificador do Município no sistema.';

COMMENT ON COLUMN DB_SINESPCT.MUNICIPIO.CO_MUNICIPIO IS 'Código do município de acordo com a TOM (Tabela de Municípios).';

COMMENT ON COLUMN DB_SINESPCT.MUNICIPIO.NO_MUNICIPIO IS 'Nome do Município de acordo com a TOM (Tabela de Municípios).';

COMMENT ON COLUMN DB_SINESPCT.MUNICIPIO.ID_UF IS 'Identificador da UF (Estado) do Município.';